### ISSUE TITLE
Including libHeif in Xcode 12+ via SPM is not working

### ISSUE THREAD

**Issue by esphynox** [SDWebImage/libheif-Xcode#1]
While using Xcode 12+ adding `libHeif` through SPM producing following error:

![Screenshot 2022-01-12 at 12 58 20](https://user-images.githubusercontent.com/8351932/149127798-aa913b8d-3336-4c69-87c3-2f617aa3ca35.png)

**Comment by dreampiggy** [comment]
Seems, libheif export the de265.h header to its public header heif.h?

I'll have a check later. The PR there seems does not solve the problem but ignore the warning from clang.

**Comment by dreampiggy** [comment]
Fixed in 1.10.0+ version again, tested with Xcode 13.4

![image](https://user-images.githubusercontent.com/6919743/170965146-6bb2f507-6252-43ba-957d-7fce639175f7.png)
