### ISSUE TITLE
Build error due to Legacy Build System

### ISSUE THREAD

**Issue by hvsw** [SDWebImage/libheif-Xcode#3]
# Context
Currently, you cannot build `master` branch due to `libde265-Xcode` at `1.0.8` due to `Cartfile.resolved` using Legacy Build System which is now deprecated in Xcode 13.4.

I created [this issue](https://github.com/SDWebImage/libde265-Xcode/issues/6) in libde265-Xcode asking to release a new version in Carthage so this project can use it.

Workaround: specify dependency to point to at least [43a87a1bef850fed5646875d2e965e349ceef3aa](https://github.com/SDWebImage/libde265-Xcode/commit/43a87a1bef850fed5646875d2e965e349ceef3aa).

Same issue in other repos:
https://github.com/SDWebImage/SDWebImageHEIFCoder/issues/26
https://github.com/SDWebImage/libde265-Xcode/issues/6

# Steps to repro
1. `git clone git@github.com:SDWebImage/libheif-Xcode.git`
3. `carthage update --platform iOS`

```
 henrique@Henrique-Valcanaia-MacBook-Pro: ~/Developer/SDWebImageHEIFCoder: master: carthage update --platform iOS
*** Fetching libheif-Xcode
*** Fetching SDWebImage
*** Fetching libde265-Xcode
*** Checking out SDWebImage at "5.12.5"
*** Checking out libde265-Xcode at "1.0.8"
*** Checking out libheif-Xcode at "1.9.0"
*** xcodebuild output can be found in /var/folders/xp/l3qg7cxs1kg8hqy4lxd4dpj40000gn/T/carthage-xcodebuild.dlsvI3.log
*** Building scheme "libde265-iOS" in libde265.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/henrique/Developer/SDWebImageHEIFCoder/Carthage/Checkouts/libde265-Xcode/libde265.xcodeproj -scheme libde265-iOS -configuration Release -derivedDataPath /Users/henrique/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4_13F17a/libde265-Xcode/1.0.8 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/xp/l3qg7cxs1kg8hqy4lxd4dpj40000gn/T/libde265-Xcode SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/henrique/Developer/SDWebImageHEIFCoder/Carthage/Checkouts/libde265-Xcode)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/xp/l3qg7cxs1kg8hqy4lxd4dpj40000gn/T/carthage-xcodebuild.dlsvI3.log
```

**Comment by dreampiggy** [comment]
Fixed in 1.10.0+ version (latest 1.12.0)

This bump the min dependency of `libde265` to `1.0.9-beta`
