### ISSUE TITLE
This libheif need upgrade to the latest version, we need higher version from libheif-sharp (C#) binding

### ISSUE THREAD

**Issue by prabhav-mehra** [SDWebImage/libheif-Xcode#5]
Hi, I built the libheif.a using the following project but the lib is missing the following methods:

 ```
Undefined symbols for architecture arm64:
    "_heif_context_get_region_item", referenced from:
       -u command line option
    "_heif_context_set_max_decoding_threads", referenced from:
       -u command line option
    "_heif_decoder_descriptor_get_id_name", referenced from:
       -u command line option
    "_heif_decoder_descriptor_get_name", referenced from:
       -u command line option
    "_heif_deinit", referenced from:
       -u command line option
    "_heif_get_decoder_descriptors", referenced from:
       -u command line option
    "_heif_image_get_content_light_level", referenced from:
       -u command line option
    "_heif_image_get_decoding_warnings", referenced from:
       -u command line option
    "_heif_image_get_mastering_display_colour_volume", referenced from:
       -u command line option
    "_heif_image_get_pixel_aspect_ratio", referenced from:
       -u command line option
    "_heif_image_handle_add_region_item", referenced from:
       -u command line option
    "_heif_image_handle_get_item_id", referenced from:
       -u command line option
    "_heif_image_handle_get_list_of_region_item_ids", referenced from:
       -u command line option
    "_heif_image_handle_get_number_of_region_items", referenced from:
       -u command line option
    "_heif_image_has_content_light_level", referenced from:
       -u command line option
    "_heif_image_has_mastering_display_colour_volume", referenced from:
       -u command line option
    "_heif_image_set_content_light_level", referenced from:
       -u command line option
    "_heif_image_set_mastering_display_colour_volume", referenced from:
       -u command line option
    "_heif_image_set_pixel_aspect_ratio", referenced from:
       -u command line option
    "_heif_init", referenced from:
       -u command line option
    "_heif_item_add_property_user_description", referenced from:
       -u command line option
    "_heif_item_get_properties_of_type", referenced from:
       -u command line option
    "_heif_item_get_property_transform_crop_borders", referenced from:
       -u command line option
    "_heif_item_get_property_transform_mirror", referenced from:
       -u command line option
    "_heif_item_get_property_transform_rotation_ccw", referenced from:
       -u command line option
    "_heif_item_get_property_type", referenced from:
       -u command line option
    "_heif_item_get_property_user_description", referenced from:
       -u command line option
    "_heif_item_get_transformation_properties", referenced from:
       -u command line option
    "_heif_mastering_display_colour_volume_decode", referenced from:
       -u command line option
    "_heif_property_user_description_release", referenced from:
       -u command line option
    "_heif_region_get_ellipse", referenced from:
       -u command line option
    "_heif_region_get_ellipse_transformed", referenced from:
       -u command line option
    "_heif_region_get_point", referenced from:
       -u command line option
    "_heif_region_get_point_transformed", referenced from:
       -u command line option
    "_heif_region_get_polygon_num_points", referenced from:
       -u command line option
    "_heif_region_get_polygon_points", referenced from:
       -u command line option
    "_heif_region_get_polygon_points_transformed", referenced from:
       -u command line option
    "_heif_region_get_polyline_num_points", referenced from:
       -u command line option
    "_heif_region_get_polyline_points", referenced from:
       -u command line option
    "_heif_region_get_polyline_points_transformed", referenced from:
       -u command line option
    "_heif_region_get_rectangle", referenced from:
       -u command line option
    "_heif_region_get_rectangle_transformed", referenced from:
       -u command line option
    "_heif_region_get_type", referenced from:
       -u command line option
    "_heif_region_item_add_region_ellipse", referenced from:
       -u command line option
    "_heif_region_item_add_region_point", referenced from:
       -u command line option
    "_heif_region_item_add_region_polygon", referenced from:
       -u command line option
    "_heif_region_item_add_region_polyline", referenced from:
       -u command line option
    "_heif_region_item_add_region_rectangle", referenced from:
       -u command line option
    "_heif_region_item_get_id", referenced from:
       -u command line option
    "_heif_region_item_get_list_of_regions", referenced from:
       -u command line option
    "_heif_region_item_get_number_of_regions", referenced from:
       -u command line option
    "_heif_region_item_get_reference_size", referenced from:
       -u command line option
    "_heif_region_item_release", referenced from:
       -u command line option
    "_heif_region_release_many", referenced from:
       -u command line option
  ld: symbol(s) not found for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

https://github.com/xamarin/xamarin-macios/issues/19064#issuecomment-1729224033

**Comment by prabhav-mehra** [comment]
@dreampiggy

**Comment by prabhav-mehra** [comment]
I didn't change framework 's MACH_O_TYPE into staticlib, is that the issue?

**Comment by prabhav-mehra** [comment]
This might be bause the the submodule reference is an old one to `libheif`. Can we update the submodule reference to 1.16.2/latest one?

**Comment by dreampiggy** [comment]
Change `MACH_O_TYPE ` into `staticlib`, and run `carthage update`(it will generate `libde265.framework`), then `xcodebuild archive libheif-iOS`, finished.

If you need manual way for xcode building, maybe you can check some online resource firstly.

https://medium.com/game-tech-tutorial/how-to-build-a-static-dynamic-framework-for-ios-90baf9bccf7e

**Comment by dreampiggy** [comment]
Or more stupid, run

```
echo 'github "SDWebImage/libheif-Xcode" >= 1.6.0' > Cartfile
carthage build --platform ios --use-xcframeworks
```

Then the `libheif.framework` and `libde265.framework` can be found in `Carthage/Build` folder.

**Comment by prabhav-mehra** [comment]
But wouldn’t it still have a reference to the older version of libheif. Based on the older submodule reference

**Comment by dreampiggy** [comment]
> But wouldn’t it still have a reference to the older version of libhei

https://github.com/SDWebImage/libheif-Xcode/commit/3a183445752ca78426edf8de27568e10fd3a6b74 Isn't this v1.12.0 ?

**Comment by dreampiggy** [comment]
I don't get your question actually. Are you mean:

> We're using a binary which dependent on libheif higher version (like 1.15.0), but libheif-Xcode does not update with the latest version ?

Because from the linker output, the `heif_context_get_region_item` API does not exists on v1.12.0, but higher version

If so, this issue title should be:

> Please upgrade to the latest libheif version (like 1.16.2) ~

**Comment by dreampiggy** [comment]
This libheif repo seems didn't upgrade during 2 years, there are many release in upstream

![image](https://github.com/SDWebImage/libheif-Xcode/assets/6919743/24e663ce-a057-4167-8d0c-4f33a334155d)
![image](https://github.com/SDWebImage/libheif-Xcode/assets/6919743/19104a24-c5cd-4ce6-b086-47402d75d5c7)

**Comment by dreampiggy** [comment]
I'v update the issue title to make it more clear, does this match your actual question ?

I may try to release from v1.12.0->v1.16.2 in these days, sometimes it does not only need to bump git submodule, also need some Xcodeproject changes, source-code hack changes (Because libheif does not know Xcode, right ? I hack some template code to make this compatible)

**Comment by prabhav-mehra** [comment]
Yes that’s correct. Bumping the version to use latest release of libheif would be great. Thanks

**Comment by prabhav-mehra** [comment]
@dreampiggy do you know what time timeline for this could look like? would love to get it working as I require it for some testing somethings using libheif asap. I could change the submodule ref myself locally but as suggested it requires more changes than that

Thanks for the help.

**Comment by dreampiggy** [comment]
If you just need ar archive, you can build from libheif's official repo using cmake && ninja && yasm

Do not need my Xcode project port actually. This port is used for Package Manager (SPM/CocoaPods) integration mostly.

At least need days, maybe before 29th vacation.

**Comment by dreampiggy** [comment]
I don't know what version you need. I already upgrade the v1.14.0~1.15.0 (4 versions). Can you provide the libheif version you need ?

Each upgrade need to build the library locally, which waste some time...

**Comment by dreampiggy** [comment]
Is this one ?

https://github.com/Cykooz/libheif-sys/blob/master/CHANGELOG.md#1160---2023-06-21

**Comment by dreampiggy** [comment]
Done, released 10 versions from v1.13.0 to v1.16.2 🥱
Cost me 4 hours totally. And some other related repo like:

1. https://github.com/SDWebImage/SVT-AV1-Xcode
2. https://github.com/SDWebImage/libde265-Xcode
3. https://github.com/SDWebImage/librav1e-Xcode

**Comment by dreampiggy** [comment]
<img width="331" alt="截屏2023-09-27 21 37 14" src="https://github.com/SDWebImage/libheif-Xcode/assets/6919743/61a3d640-b07c-4a06-a32f-7bd2d2cd8d4c">

**Comment by dreampiggy** [comment]
As my explained. You can always build by yourself using `cmake` with `ninja`, if you only need iOS arm64 build with libde265

This repo's goal is 

> Make libheif (or other C/C++ cross-platform repo) who use `cmake/make/automake` etc, universally transform to iOS/macOS/tvOS/watchOS/visionOS 's native package manager, with the proper dependency

> iOS native developer only use Cocoapods/SwiftPM/Carthage(Xcode itself), they don't install `cmake` or `ninja` at all, or even don't know what's that is


Using source code to integrate means better `Debugger support`, dynamic/static linkage switching (some user may choose to dylib dlopen), xcframework support, or more. Beyond that simple `.a` ar archive.
